### ISSUE TITLE
os.makedirs "exist_ok" does not exist in Python 2

### ISSUE THREAD

**Issue by maaaaz** [vulnersCom/getsploit#16]
Hello there,

In its pip package `getsploit` informs that Python 2 is supported to run it.
But in Python 2 `os.makedirs` [does not have](https://docs.python.org/2.7/library/os.html#os.makedirs) an [`exist_ok`](https://github.com/vulnersCom/getsploit/blob/master/getsploit/getsploit.py#L37) option so it does not work:
```
New in version 3.2: The exist_ok parameter.
```

Cheers.

**Comment by vulnersCom** [comment]
Fixed
https://github.com/vulnersCom/getsploit/commit/ee89264fd1970c50fcd6f54d3a727d89cea578f8
