### ISSUE TITLE
Please provide a real offline mode

### ISSUE THREAD

**Issue by maaaaz** [vulnersCom/getsploit#17]
Hello,
Could you provide a real offline mode ?

Because to date, `getsploit` still needs an Internet connection even with the offline database, as one of the first actions in the script is to call [this function](https://github.com/vulnersCom/getsploit/blob/master/getsploit/getsploit.py#L145) which performs a check of the authenticity of the key.

Cheers.

**Comment by vulnersCom** [comment]
Fixed in 

https://github.com/vulnersCom/getsploit/commit/d878358daa25139ccc45d76d2ebd91375a24172f
